---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: minio

images:
  - name: minio-server
    newName: docker.io/minio/minio
    newTag: "RELEASE.2021-04-06T23-11-00Z"

...
