---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

secretGenerator:
  - name: minio-server
    options:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/component: server
    literals: []

...
